### ISSUE TITLE
nftables PostDown doesn't work

### ISSUE THREAD

**Issue by TCB13** [burghardt/easy-wg-quick#109]
Hello,

The current way rules are removed doesn't work in nft. Here is an example:
````
nft delete rule inet filter forward iifname $WG_IF accept
Error: syntax error, unexpected iifname, expecting handle
delete rule inet filter forward iifname accept
                                ^^^^^^^
````

Unlike `iptables` nft seems to require the user to give it an handle for the rule that can be found with something like `nft -a list ruleset`.

Are there any plans for a better way to handle this? Thank you.

**Comment by burghardt** [comment]
It looks like chains and tables do not need handles to be removed. Maybe I could use per-instance chains and drop them with all their rules.

**Comment by TCB13** [comment]
Great! Thanks.
