### ISSUE TITLE
The port number is not changing

### ISSUE THREAD

**Issue by adeel14553** [burghardt/easy-wg-quick#134]
No wghub.conf... creating one!
WireGuard hub address is 10.15.136.220:41194 on eth0.

interface: wghub
  public key: xxxxxxxxxxx+23OxUHDYfEgHkI=
  private key: (hidden)
  listening port: 62707

cat portno.txt 
41194

**Comment by burghardt** [comment]
Have you updated the network interface after creating a new configuration file?

**Comment by burghardt** [comment]
Closing this issue as inactive. If this is still the case, please reopen and provide more details.
