### ISSUE TITLE
pls centos8 support

### ISSUE THREAD

**Issue by Pomazan-Bogdan** [burghardt/easy-wg-quick#17]
[centos@srv1 wg]$ sudo yum install wireguard mawk grep iproute2 qrencode
Last metadata expiration check: 0:43:12 ago on Sun 08 Dec 2019 03:33:11 PM CET.
No match for argument: wireguard
No match for argument: mawk
Package grep-3.1-6.el8.x86_64 is already installed.
No match for argument: iproute2
Error: Unable to find a match

**Comment by burghardt** [comment]
```
sudo dnf install wireguard-tools gawk grep iproute qrencode
```

To include `wireguard-tools` in available available packages list read [wireguard.com/install](https://www.wireguard.com/install/).

**Comment by Pomazan-Bogdan** [comment]
`[centos@srv1 ~]$ sudo dnf install wireguard-tools gawk grep iproute qrencode
Last metadata expiration check: 0:53:30 ago on Tue 10 Dec 2019 07:39:31 AM CET.
Package wireguard-tools-1:0.0.20191206-1.el8.x86_64 is already installed.
Package gawk-4.2.1-1.el8.x86_64 is already installed.
Package grep-3.1-6.el8.x86_64 is already installed.
Package iproute-4.18.0-11.el8.x86_64 is already installed.
Package qrencode-3.4.4-5.el8.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
`

WG up, client connect, but internet not work (

**Comment by burghardt** [comment]
Redact keys and post your configuration.

**Comment by Pomazan-Bogdan** [comment]
[Interface]
Address = 10.127.0.11/24, fdfc:2965:0503:e2ae::11/64
DNS = 1.1.1.1, 2606:4700:4700::1111
PrivateKey = sEqaaTqa05iX/ZbZkEkMM1bveXChJ3r6u1YcY6srjW4=

[Peer]
PublicKey = 4p4s64L1qkQrGiUMDlppq87aLWqtM01UhhlVKsgiQxA=
PresharedKey = o5efiOLqBZWpVN5P2+sZEzP2zBxqtnSRoZasCALyqCs=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 194.182.67.126:17596
PersistentKeepalive = 25

**Comment by Pomazan-Bogdan** [comment]
[Interface]
Address = 10.127.0.1/24
ListenPort = 17596
PrivateKey = 0MCxGDeCuAxTGOXXRCckCVfzP4OOJwfmO2ebzq*****
SaveConfig = false

PostUp = iptables -t mangle -A POSTROUTING -p tcp --tcp-flags SYN,RST SYN -o eth0 -j TCPMSS --clamp-mss-to-pmtu
PostUp = ip6tables -t mangle -A POSTROUTING -p tcp --tcp-flags SYN,RST SYN -o eth0 -j TCPMSS --clamp-mss-to-pmtu
PostUp = iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostUp = ip6tables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostUp = iptables -A FORWARD -i %i -j ACCEPT
PostUp = ip6tables -A FORWARD -i %i -j ACCEPT
PostUp = sysctl -q -w net.ipv4.ip_forward=1
PostUp = sysctl -q -w net.ipv6.conf.all.forwarding=1

PostDown = sysctl -q -w net.ipv4.ip_forward=0
PostDown = sysctl -q -w net.ipv6.conf.all.forwarding=0
PostDown = iptables -D FORWARD -i %i -j ACCEPT
PostDown = ip6tables -D FORWARD -i %i -j ACCEPT
PostDown = iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE
PostDown = ip6tables -t nat -D POSTROUTING -o eth0 -j MASQUERADE
PostDown = iptables -t mangle -D POSTROUTING -p tcp --tcp-flags SYN,RST SYN -o eth0 -j TCPMSS --clamp-mss-to-pmtu
PostDown = ip6tables -t mangle -D POSTROUTING -p tcp --tcp-flags SYN,RST SYN -o eth0 -j TCPMSS --clamp-mss-to-pmtu

# 11: 11 > wgclient_11.conf
[Peer]
PublicKey = H1czdpaba1t/Na9kwY0HNLfWgvzIMjFPgWEfPgyyGSc=
PresharedKey = o5efiOLqBZWpVN5P2+sZEzP2zBxqtnSRoZasCALyqCs=
AllowedIPs = 10.127.0.11/32, fdfc:2965:0503:e2ae::11/128

**Comment by burghardt** [comment]
> but internet not work

Config looks fine. What exactly does not work, when "internet not work"? Could you try the following:

1. Check if you can ping/traceroute your VPN hub.
2. Check if you can ping/traceroute your DNS server.
3. Check if you can ping/traceroute anything else in the Internet.
4. Check above for IPv4, if your system defaults to IPv6.
5. Check if you can resolve DNS names (i.e. host -v github.com)
6. Try to use curl/wget to reach some HTTP sites (i.e. curl -vvv https://github.com)
7. If curl/wget works for small pages, but large pages/files loading breaks check for (P)MTU issues.

If all of above work post what you were trying to do and it doesn't work.

**Comment by Pomazan-Bogdan** [comment]
> 1. Check if you can ping/traceroute your VPN hub.
Ответ от 194.182.67.126: число байт=32 время=37мс TTL=64

> 2\. eck if you can ping/traceroute your DNS server.
Fail

**Comment by burghardt** [comment]
Does your VPN hub forward packets? You can check that with `tcpdump`. Are there other firewall rules except those set by wg-quick that can block traffic? You can verify firewall setup with `ip(6)tables -vnxL`.
