### ISSUE TITLE
pf/ipfw support for FreeBSD?

### ISSUE THREAD

**Issue by soup6020** [burghardt/easy-wg-quick#19]
FreeBSD does not use iptables, the existing post up/down scripts do not work.

**Comment by soup6020** [comment]
I'll try to make a fork for this after work, but I'm not sure my knowledge of bash is enough to put FreeBSD and Linux in the same script.

**Comment by burghardt** [comment]
That's right. Even more `ip` command is not available on FreeBSD (not even in ports) so hub IP adress detection fails. I will look into BSD `ifconfig` or maybe I can switch to `curl ifconfig.me/ip` or similar service.
