### ISSUE TITLE
Suggestions for improvement

### ISSUE THREAD

**Issue by christianbur** [burghardt/easy-wg-quick#24]
I had planned to use the config script for my wireguard config, but unfortunately this is not possible due to the following points. 

- You can only customize the ipv4 DNS server (INT_NET_DNS), but not the ipv6 DNS server (INT_NET6_DNS)
- You cannot customize the internal ipv4/ipv6 networks. 
- MASQUERADE for IPv6 is always active, but mostly wireguard is used on a vpc with public ipv6 addresses (/64) so you can use /112 of the public ipv6 addresses for wireguard without problems. 
- "PostDown = sysctl -q -w net.ipv4.ip_forward=0, PostDown = sysctl -q -w net.ipv6.conf.all.forwarding=0" [can be very dangerous](https://success.docker.com/article/ipv4-forwarding), because after that e.g. Docker containers won't work anymore.  
- A single config file would be easier to maintain than many config files.

**Comment by burghardt** [comment]
Right now you can:
- customize both IPv4 and IPv6 DNS servers,
- customize the internal IPv4 and IPv6 network addresses,
- disable sysctl in PostUp/PostDown.

When comes to a single config file I prefer current solution (wontfix), as most people wont need to set up more than single `echo something > somewhere && ./easy-wg-quick`. It can be also more complicated to have single config file, as currently many of this files are populated with random data (i.e. random port, random network address, random key material) on first use.

Last thing is IPv6 without masquerading. For what I understand you want to achieve is to have IPv6 access without NAT using part (/112) of your /64 prefix assigned to VPS. This should be easy to do, but some manual steps are required.
1. Having `2001:19f0:6c01:1c0d/64` assign `...:40/112` to Wireguard interface.
```
echo '2001:19f0:6c01:1c0d:40::' > intnet6address.txt
```
2. Set `INT_NET6_MASK="/112"` in `easy-wg-quick` script (this should be changed to configuration file).
3. Generate configuration
```
./easy-wg-quick
```
4. Remove PostUp/PostDown `-j MASQUERADE` for `ip6tables` from `wghub.conf`.
5. Enable Neighbor Discovery Protocol Proxy.
```
sudo sysctl net.ipv6.conf.all.proxy_ndp=1
```
6. Add client IPv6 address to NDP on external interface (i.e. `ens3`).
```
sudo ip -6 neigh add proxy 2001:19f0:6c01:1c0d:40::10 dev ens3
```
7. Scan QR code on client and verify if this works for you.

Let me know if this is a setup you where thinking of. Probably all this steps can be automated in script.

**Comment by christianbur** [comment]
Thanks for the customizations, I'll test it out.
But I still can't get used to the many config files. Why can't you just put the internal variables into a separate config.txt file? 
The file "seqno.txt" could also remain a file, because this is a counter and does not really belong to config. 

File: config.txt
```
EXT_NET_IF="eth0"
EXT_NET_IP="1.2.3.4"
EXT_NET_PORT="54367"
INT_NET_ADDRESS="10.x.y."
INT_NET_DNS="1.1.1.1"
INT_NET_MASK="/24"
INT_NET6_ADDRESS="2a01:x:x:x::100:"
INT_NET6_DNS=""
INT_NET6_MASK="/112"
NET6MODE="proxy_ndp"
FW_TYPE="iptables"
SYSCTL_TYPE="linux"
```


```
#!/bin/bash

source config.txt

#get 
echo $EXT_NET_IF

#set 
echo "TEST_TYPE=\"test\"" >> config.txt

#change 
sed -i -e 's/'TEST_TYPE=.*'/TEST_TYPE=\"test2\"/' config.txt
```

**Comment by burghardt** [comment]
This is a bit more complicated as `EXT_NET_PORT`, `INT_NET_ADDRESS`, `INT_NET6_ADDRESS` are randomly chosen on the first run. Also, installation with a single `wget` command is very simple, but cannot ship config file. I ponder if I can generate config file on the first run then ask the user to review and customize it. Finally second run (when config already exists) generates `wghub.conf` and first client configuration.

**Comment by christianbur** [comment]
Let me describe my first experiences with the script. 
- download the script 
- execute the script
- Then I looked at the file wghub.conf and wgclient_10.conf and realized that the default values do not fit for me.
- Then open and edit every single file with vi. 
- Then I had to figure out which files to delete to reset the WG-config, but keep the config of the script. Of course I also created a default client "10", but I didn't want it.
-  After that I have created a client (with name). A Day later I wanted to transfer the config with QR Code to my iPhone. Because I didn't find a way to display the QR Code again I searched (and found) the command in the script. 

That's what I would expect.

- download the script 
- execute the script (without parameters) 
       - a short help is displayed
- ./easy-wg-quick --init
     - The config file is created and the variables EXT_NET_PORT, INT_NET_ADDRESS, INT_NET6_ADDRESS are also filled by script. 
     - An info text informs the user that he can now edit the config file manually. 
     - if necessary you can give the "--init" an additional parameter like NET6MODE="proxy_ndp".
       How to implement this easily I do not know yet.
- ./easy-wg-quick --add_client or ./easy-wg-quick --add_client iphone
    - create a new client (default or "iphone")

- ./easy-wg-quick --print_client iphone 
    - prints the qr-code for the client "iphone"
