### ISSUE TITLE
when using ipv6 public addr, the default gate way is not my wg server

### ISSUE THREAD

**Issue by youxiaojie** [burghardt/easy-wg-quick#44]
when I run wg and config an ipv6 traceroute something should be first hop my wg server, however my pc direct using the native ipv6 in stead of vpn ipv6. should there add route?

**Comment by burghardt** [comment]
Could you please post your routing table and `traceroute` output to explain the issue?

**Comment by youxiaojie** [comment]
:/ # ip route
10.6.104.140/30 dev rmnet_data0 proto kernel scope link src 10.6.104.141
10.28.73.0/24 dev tun0 proto kernel scope link src 10.28.73.10
123.123.123.123 via 10.6.104.142 dev rmnet_data0 src 10.6.104.141
:/ # ip -6 route
:/ # ip -6 route

**Comment by youxiaojie** [comment]
in ipv6 only mobile phone 
7: rmnet_data0: <UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UNKNOWN group default qlen 1000
    link/[530]
    inet6 2408:84e1:8:7:e:8:e:b/64 scope global dynamic
       valid_lft forever preferred_lft forever
    inet6 fe80::ea2b:8d96:e1b:c4ed/64 scope link
       valid_lft forever preferred_lft forever

:/ # ping6 www.google.com
^C
130|:/ # ping6 www.google.com
^C
130|:/ # ip -6 route

1|:/ # ping6 2001:4:6:5::1
PING 2001:4:6:5::1(2001:4:6:5::1) 56 data bytes
^C
--- 2001:4:6:5::1 ping statistics ---
4 packets transmitted, 0 received, 100% packet loss, time 3009ms
1|:/ # ping6 2001:4:6:5::10
PING 2001:4:6:5::10(2001:4:6:5::10) 56 data bytes
64 bytes from 2001:4:6:5::10: icmp_seq=1 ttl=64 time=0.203 ms

**Comment by youxiaojie** [comment]
try to test on computer to see where's trouble.so temp closed.
