### ISSUE TITLE
about /48 ipv6 addr.

### ISSUE THREAD

**Issue by youxiaojie** [burghardt/easy-wg-quick#45]
Neighbor Discovery Proxies (ND Proxy, NDP Proxy) allows end-to-end connectivity, but requires /64 network to be assigned to hub. From this /64 network, a subnetwork has to be divided (i.e. /112) and assigned to Wireguard interface.
dear friend, I see you mentioned ndp requires /64, if I got a /48 ipv6, can I use it in sub network? what I want is to setting wg  on top level of router(whole company), assign /48 vpn. and then devided to /64 on second level router(each department), for  slaac ipv6 in vpn, is it feasible? /112 will not be used in slaac.

**Comment by burghardt** [comment]
From network perspective /48 can be divided into /64. On the other hand [easy-wg-quick:373](../blob/33614c9365d4d903b740fd5c572a93858e91a807/easy-wg-quick#L373) generates NDP proxy entries only for directly connected WG peers. Are you sure NDP proxy is the way top level company routers should be configured?
