### ISSUE TITLE
about saveconfig=true

### ISSUE THREAD

**Issue by youxiaojie** [burghardt/easy-wg-quick#47]
in man wg-quick, 
`For use on a server, the following is a more complicated example involving multiple peers:

           [Interface]
           Address = 10.192.122.1/24
           Address = 10.10.0.1/16
           SaveConfig = true
           PrivateKey = yAnz5TF+lXXJte14tji3zlMNq+hd2rYUIgJBgB3fBmk=
           ListenPort = 51820

           [Peer]
           PublicKey = xTIBA5rboUvnH4htodjb6e697QjLERt1NAB4mZqp8Dg=
           AllowedIPs = 10.192.122.3/32, 10.192.124.1/24

           [Peer]
           PublicKey = TrMvSoP4jYQlY6RIzBgbssQqY3vxI2Pi+y71lOWWXX0=
           AllowedIPs = 10.192.122.4/32, 192.168.0.0/16

           [Peer]
           PublicKey = gN65BkIKy1eCE9pP1wdc8ROUtkHLF2PfAqYdyYBz6EA=
           AllowedIPs = 10.10.10.230/32

       Notice the two `Address' lines at the top, and that `SaveConfig' is set to `true', indicating that the configuration
       file should be saved on shutdown using the current status of the interface.
`

but your setting is false, why?

**Comment by burghardt** [comment]
The easy-wg-quick script is a configuration generator. I do not expect anyone to modify loaded configuration on the fly and save it back to the config file. If you use `wg set` to change configuration it might no longer be editable by the script.

If you created configuration with easy-wg-quick and wan to customize it on the fly with `wg set` install a copy of `wghub.conf` to `/etc/wireguard`, change `SaveConfig = flase` to `true` and load it. It safe to edit the copy, but when you add new peers using the script you will need to do some manual merging of the files.

Could you describe a bit of what you change on the interface configuration that you want to save when bringing it down? I'm interested in cases it is useful for.

**Comment by youxiaojie** [comment]
1. I ask this question because I meet a question about openwrt wireguard. the openwrt could not roam, when I move openwrt to a new place I must to restart server side to get received data. I run wg in server side, find endpoint does not changed. but the client in mobile phone is ok. I deal with this question with a server side watchdog. 
2. I modify your wghub.conf manually to be an ipv6 tunnel broker. I got a /48 v6 from vps. using wireguard to home router, and signed it to following pcs.
server:
[Interface]
Address = 10.xx.xx.1/24, fd39:xxxx:xxxx:xxxx::1/64, 2001:470:xxxx::1/48
# 10: openwrt > wgclient_openwrt.conf
[Peer]
AllowedIPs = 10.xx.xx.10/32, fd39:xxxx:xxxx:xxxx::10/128, 2001:470:xxxx::10/128, 2001:470:xxxx:100::/56 # the subnet PD to routers

client:
# 10: openwrt > wgclient_openwrt.conf
[Interface]
Address = 10.xx.xx.10/24, fd39:xxxx:xxxx:xxxx::10/64, 2001:470:xxxx::10/64
DNS = 1.1.1.1, 2606:4700:4700::1111

[Peer]
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = x.x.x.x:abcd
PersistentKeepalive = 25

thanks!

**Comment by burghardt** [comment]
1. For this single hub and multiple peers configuration hub never tries to initiate any connection with peers (no `Endpoints` defined in `wghub.conf`). It's a peer who initiates the connection and updates the server with its current IP each time it transmits anything (and if there's no need to transmit anything for 25 seconds keep-alive set in `PersistentKeepalive` kicks in).
2. That's interesting. Did you debug why routers couldn't ping each other?
3. This script never generates multiple `Address` statements. IPv4 and IPv6 addresses are put in a single line if you use `cat ...>intnet6address.txt`.
