### ISSUE TITLE
SSH tunnels not working

### ISSUE THREAD

**Issue by OSHW-Rico** [burghardt/easy-wg-quick#56]
Thanks for your work at first! :+1: 

I have setup everything according to your instructions and it works kinda as expected. At least for standart web traffic. Ping and traceroutes are running fine throught the tunnel. But i can not establish ssh tunnels throught the wireguard VPN. Not to other clients in the VPN, not to the Peer, not to public servers.

Any idea what could be wrong.

```
debug1: Authenticating to xxx as 'rico'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: ecdsa-sha2-nistp256
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
```

right there the ssh connection attempt stalls.

I appreciate any tipps. Thanks!

**Comment by burghardt** [comment]
Could you provide information on the customization you have done to the default `easy-wg-quick` configuration (i.e., firewall type, firewall rules). If web access to some sites is also problematic, it could be MTU issues (PMTU issues, ICMP message restrictions too tight, TCPMSS module disabled).

Could you try to dump the network traffic on both sides of the tunnel to the file (i.e., with the `tcpdump -w`) during the SSH session setup attempt and upload them here?

**Comment by rs-development** [comment]
Ahh i forget to replay. I could not reproduce the issue reliably. It has not occurred in the last two weeks or so. I would assume it is unrelated to your scripts.
