### ISSUE TITLE
the client config used by openwrt has something wrong

### ISSUE THREAD

**Issue by youxiaojie** [burghardt/easy-wg-quick#57]
```
root@racknerd-4afe10:~/wg# cat wgclient_wghub.uci.txt 
# 10: wghub > wgclient_wghub.uci.txt
config interface 'wg0'
        option proto 'wireguard'
        option listen_port '28894' //this port should be in peer section! the server side's port
        list addresses '10.x.x.x/24'
        list addresses '2001:470:x:x:1::10/112'
        list dns '1.1.1.1'
        list dns '2606:4700:4700::1111'
        option private_key ''
config wireguard_wg0
        option allowed_ips '0.0.0.0/0' //this should be list allow_ips........
        option route_allowed_ips '1'
        option endpoint_host 'x.x.x.x'
        option endpoint_port '28894' //this is correct
        option persistent_keepalive '25'
        option public_key ''
        option preshared_key ''

```

**Comment by burghardt** [comment]
> option listen_port '28894' //this port should be in peer section! the server side's port

This makes the client listen on that port. It's perfectly fine in that part of the configuration. It doesn't belong to the pear configuration. Do you think it could be skipped?

> option allowed_ips '0.0.0.0/0' //this should be list allow_ips

Yes, this is a bug and needs to be fixed. Thank you for catching that!

**Comment by burghardt** [comment]
Looks like option `listen_port` is not required for peers. I will remove it.

**Comment by youxiaojie** [comment]
> > option listen_port '28894' //this port should be in peer section! the server side's port
> 
> This makes the client listen on that port. It's perfectly fine in that part of the configuration. It doesn't belong to the pear configuration. Do you think it could be skipped?
I think as your title wgclient_wghub.uci.txt, this plays as client role, so option listen_port '28894' in interface could be omit. but to add this will be possible to be actively connected by other peer. I take care of the peer behind nat, this port results in no sense.
