### ISSUE TITLE
when using ndp, the client can mtr to public ipv6, but public ipv6 could not mtr to client ipv6.

### ISSUE THREAD

**Issue by youxiaojie** [burghardt/easy-wg-quick#58]
when using ndp, the client can mtr to public ipv6, but public ipv6 could not mtr to client ipv6.
should we also include an individual route for clint ipv6 to wg port?

**Comment by burghardt** [comment]
Could you share information about what the problem was? As you closed this issue, I assume you resolved it yourself.
