### ISSUE TITLE
config for ds-lite isp link

### ISSUE THREAD

**Issue by FSTNDonald** [burghardt/easy-wg-quick#69]
Hi,
this script is really great, plenty of supporting files/scripts are generated automatically.

Unfortunately I cannot get my config running for peers outside of local LAN, i.e. 'dialing in' from remote.
My ISP link is ds-lite (dual stack lite), i.e. only the IPv6 address of my WG hub is global/public, his IPv4 is not reachable from outside.

I am not trying to tunnel IPv6 encapsulated in WG IPv4 link, but just the other way around. The dialing-in peer (iOS) shall call the IPv6 address only of the WG hub and establish a tunnel carrying at least IPv6, carrying/routing IPv4 also would be of substantial benefit of course.

I think, "wg show" on the hub reveals the problem:
  preshared key: (hidden)
  endpoint: 192.168.0.36:62927
  allowed ips: 10.50.43.15/32, 2a00:xxxx:xxxx:xxxx:xxxx:32ff:fe39:15/128
  latest handshake: 15 minutes, 58 seconds ago
  transfer: 283.10 KiB received, 1.81 MiB sent
The "endpoint", which is the same as in the client config, is not the global IPv6 of the WG hub, but some local LAN IPv4 address ... ???

Some advice, how to eleminate IPv4 for dialing-in out of the scripts, is very much appreaciated. I tried to replace IPv4 addresses by IPv6, but that broke the script (wg-quick not starting service and client refusing to load the QR config).

Best Regards - Donald

**Comment by Kittenmoon21** [comment]
Thank you I have a lot more to learn

**Comment by burghardt** [comment]
Try `echo '[address]' > extnetip.txt` (note `[` and `]` around the address). This should help with QRcode issue. README.md was updated in #90 to mention this.
